In [1]:
import torch

# Tensor Initialisation

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [7]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.5744, 0.4875, 0.3776],
        [0.9162, 0.6523, 0.7495],
        [0.1820, 0.5714, 0.4173],
        [0.7968, 0.4956, 0.7787],
        [0.6377, 0.1953, 0.7333]])


In [8]:
# torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# check size
print(x.size())

torch.Size([5, 3])


In [10]:
# check data type
print(x.dtype)

torch.float32


In [11]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [12]:
# check type
print(x.dtype)

torch.float16


In [13]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [14]:
# requires_grad argument
x = torch.tensor([5.5, 3], requires_grad=True)
print (x)

tensor([5.5000, 3.0000], requires_grad=True)


# Operation on Tensors

In [15]:
# Define tensors
x = torch.tensor([5.5, 3], requires_grad=True)  # Tensor with gradient tracking
y = torch.tensor([5.5, 3], requires_grad=False) # Tensor without gradient tracking

# Perform an operation
z = x.sum() + y.sum()
print("Value of z:", z.item())

# Backward pass to compute gradients
z.backward()

# Print gradients
print("Gradient for x (requires_grad=True):", x.grad)
print("Gradient for y (requires_grad=False):", y.grad)

Value of z: 17.0
Gradient for x (requires_grad=True): tensor([1., 1.])
Gradient for y (requires_grad=False): None


In [16]:
# Operations on Tensors
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
# elementwise addition
z = x + y
# torch.add(x,y) 
print (z)

tensor([[0.9305, 0.7232],
        [0.5720, 0.2623]])
tensor([[0.8048, 0.7136],
        [0.9335, 0.8674]])
tensor([[1.7353, 1.4368],
        [1.5055, 1.1298]])


In [17]:
# subtraction
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x - y
z = torch.sub(x, y)
print (z)

tensor([[0.0841, 0.8225],
        [0.5148, 0.6935]])
tensor([[0.2228, 0.4538],
        [0.5790, 0.1362]])
tensor([[-0.1387,  0.3687],
        [-0.0642,  0.5572]])


In [18]:
# multiplication
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x * y
z = torch.mul(x,y)
print (z)


tensor([[0.9926, 0.5182],
        [0.1105, 0.5038]])
tensor([[3.8457e-04, 7.7160e-01],
        [7.6297e-01, 1.9794e-01]])
tensor([[3.8173e-04, 3.9982e-01],
        [8.4299e-02, 9.9728e-02]])


In [19]:
# division
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z1 = x / y
z1 = torch.div(x,y)
print(z1)

tensor([[0.6627, 0.3730],
        [0.0605, 0.5017]])
tensor([[0.2880, 0.8147],
        [0.3714, 0.4041]])
tensor([[2.3006, 0.4578],
        [0.1628, 1.2415]])


# Slicing

In [20]:
#Slicing
x = torch.rand(5,3)
print("Slicing")
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

Slicing
tensor([[0.7215, 0.8731, 0.7681],
        [0.6993, 0.1462, 0.2795],
        [0.4448, 0.0993, 0.4979],
        [0.2036, 0.6899, 0.0501],
        [0.0407, 0.4294, 0.7499]])
tensor([0.7215, 0.6993, 0.4448, 0.2036, 0.0407])
tensor([0.6993, 0.1462, 0.2795])
tensor(0.1462)
0.14620119333267212


# Reshaping Tensors

In [21]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

tensor([[ 0.1931, -0.2556, -1.8057,  1.1323],
        [-1.6662,  0.7245,  0.1843, -0.2348],
        [ 0.2681, -1.0996,  0.4383, -0.4840],
        [ 0.0267, -1.1624, -0.0948, -0.5101]])
tensor([ 0.1931, -0.2556, -1.8057,  1.1323, -1.6662,  0.7245,  0.1843, -0.2348,
         0.2681, -1.0996,  0.4383, -0.4840,  0.0267, -1.1624, -0.0948, -0.5101])
tensor([[ 0.1931, -0.2556, -1.8057,  1.1323, -1.6662,  0.7245,  0.1843, -0.2348],
        [ 0.2681, -1.0996,  0.4383, -0.4840,  0.0267, -1.1624, -0.0948, -0.5101]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# NumPy

In [22]:
# Numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# If the Tensor is on the CPU, they will share the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
# Numpy to Torch
print("Numpy to Torch")
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)


Numpy to Torch
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:
#They also share same memory
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Autograd Package

In [38]:
# The Autograd Package
print("Autograd Package")
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):

    random = False
    if random:    
        random_inputs = torch.randn(4)
        print(random_inputs)
    else:
        random_inputs = 3

    # just a dummy example
    model_output = (weights*random_inputs).sum() # [1,1,1,1]*3 = [3,3,3,3] => 3*4 = 12
    print(model_output)
    
    model_output.backward() # calculate gradients 
    print(weights.grad) # dLoss/dw
    print(weights)

    with torch.no_grad():
        weights -= 0.1 * weights.grad
        print(weights)

    # this is important! It affects the final weights & output
    weights.grad.zero_() # the gradient will accumulate otherwise

print(weights)
print(model_output)

Autograd Package
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([1., 1., 1., 1.], requires_grad=True)
tensor([0.7000, 0.7000, 0.7000, 0.7000], requires_grad=True)
tensor(8.4000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.7000, 0.7000, 0.7000, 0.7000], requires_grad=True)
tensor([0.4000, 0.4000, 0.4000, 0.4000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.4000, 0.4000, 0.4000, 0.4000], requires_grad=True)
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
