In [2]:
import torch

In [3]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [4]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([0., 0., 0.])


In [5]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[2.2726e-37, 6.4460e-43, 2.2726e-37],
        [6.4460e-43, 2.2719e-37, 6.4460e-43]])


In [6]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [7]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [8]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.3153, 0.6180, 0.8918],
        [0.7918, 0.5268, 0.0336],
        [0.6340, 0.6235, 0.6433],
        [0.1785, 0.6831, 0.8864],
        [0.9716, 0.0831, 0.0300]])


In [9]:
# torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# check size
print(x.size())

torch.Size([5, 3])


In [11]:
# check data type
print(x.dtype)

torch.float32


In [12]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [13]:
# check type
print(x.dtype)

torch.float16


In [14]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [15]:
# requires_grad argument
x = torch.tensor([5.5, 3], requires_grad=True)
print (x)

tensor([5.5000, 3.0000], requires_grad=True)


In [16]:
# Define tensors
x = torch.tensor([5.5, 3], requires_grad=True)  # Tensor with gradient tracking
y = torch.tensor([5.5, 3], requires_grad=False) # Tensor without gradient tracking

# Perform an operation
z = x.sum() + y.sum()
print("Value of z:", z.item())

# Backward pass to compute gradients
z.backward()

# Print gradients
print("Gradient for x (requires_grad=True):", x.grad)
print("Gradient for y (requires_grad=False):", y.grad)

Value of z: 17.0
Gradient for x (requires_grad=True): tensor([1., 1.])
Gradient for y (requires_grad=False): None


In [17]:
# Operations on Tensors
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
# elementwise addition
z = x + y
# torch.add(x,y) 
print (z)

tensor([[0.9986, 0.9142],
        [0.4213, 0.7658]])
tensor([[0.8177, 0.2493],
        [0.8877, 0.5194]])
tensor([[1.8163, 1.1635],
        [1.3090, 1.2852]])


In [18]:
# subtraction
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x - y
z = torch.sub(x, y)
print (z)

tensor([[0.7369, 0.3606],
        [0.9906, 0.1060]])
tensor([[0.9953, 0.8562],
        [0.3625, 0.0099]])
tensor([[-0.2585, -0.4956],
        [ 0.6281,  0.0961]])


In [19]:
# multiplication
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x * y
z = torch.mul(x,y)
print (z)


tensor([[0.5601, 0.1591],
        [0.4636, 0.4394]])
tensor([[0.8626, 0.0657],
        [0.9865, 0.6749]])
tensor([[0.4832, 0.0104],
        [0.4574, 0.2966]])


In [20]:
# division
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z1 = x / y
z1 = torch.div(x,y)
print(z1)

tensor([[0.9033, 0.8558],
        [0.8650, 0.6454]])
tensor([[0.9727, 0.3998],
        [0.0143, 0.6681]])
tensor([[ 0.9287,  2.1406],
        [60.6657,  0.9660]])


In [21]:
#Slicing
x = torch.rand(5,3)
print("Slicing")
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

Slicing
tensor([[0.1561, 0.3913, 0.3510],
        [0.3542, 0.5758, 0.6813],
        [0.2402, 0.9190, 0.9829],
        [0.5736, 0.8801, 0.6445],
        [0.4977, 0.8069, 0.2295]])
tensor([0.1561, 0.3542, 0.2402, 0.5736, 0.4977])
tensor([0.3542, 0.5758, 0.6813])
tensor(0.5758)
0.5757880806922913


In [22]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

tensor([[ 0.5361,  1.6673, -0.7787, -0.3176],
        [ 1.3707,  1.1793,  0.7998,  0.0828],
        [ 1.5873,  0.0245,  0.4463,  1.4418],
        [-0.0758,  1.2684, -0.7917, -0.7320]])
tensor([ 0.5361,  1.6673, -0.7787, -0.3176,  1.3707,  1.1793,  0.7998,  0.0828,
         1.5873,  0.0245,  0.4463,  1.4418, -0.0758,  1.2684, -0.7917, -0.7320])
tensor([[ 0.5361,  1.6673, -0.7787, -0.3176,  1.3707,  1.1793,  0.7998,  0.0828],
        [ 1.5873,  0.0245,  0.4463,  1.4418, -0.0758,  1.2684, -0.7917, -0.7320]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# Numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# If the Tensor is on the CPU, they will share the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
# Numpy to Torch
print("Numpy to Torch")
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)


Numpy to Torch
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
#They also share same memory
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
# The Autograd Package
print("Autograd Package")
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    
    model_output.backward()
    print(weights.grad)

    with torch.no_grad():
        weights -= 0.1 * weights.grad

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

Autograd Package
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
