In [1]:
import torch

# Tensor Initialisation

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [7]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.0569, 0.7306, 0.2060],
        [0.1411, 0.4123, 0.6456],
        [0.6659, 0.1046, 0.6089],
        [0.4827, 0.9720, 0.5592],
        [0.1343, 0.3883, 0.7732]])


In [8]:
# torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# check size
print(x.size())

torch.Size([5, 3])


In [10]:
# check data type
print(x.dtype)

torch.float32


In [11]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [12]:
# check type
print(x.dtype)

torch.float16


In [13]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [14]:
# requires_grad argument
x = torch.tensor([5.5, 3], requires_grad=True)
print (x)

tensor([5.5000, 3.0000], requires_grad=True)


# Operation on Tensors

In [15]:
# Define tensors
x = torch.tensor([5.5, 3], requires_grad=True)  # Tensor with gradient tracking
y = torch.tensor([5.5, 3], requires_grad=False) # Tensor without gradient tracking

# Perform an operation
z = x.sum() + y.sum()
print("Value of z:", z.item())

# Backward pass to compute gradients
z.backward()

# Print gradients
print("Gradient for x (requires_grad=True):", x.grad)
print("Gradient for y (requires_grad=False):", y.grad)

Value of z: 17.0
Gradient for x (requires_grad=True): tensor([1., 1.])
Gradient for y (requires_grad=False): None


In [16]:
# Operations on Tensors
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
# elementwise addition
z = x + y
# torch.add(x,y) 
print (z)

tensor([[0.5542, 0.5852],
        [0.4905, 0.0297]])
tensor([[0.1985, 0.8337],
        [0.6419, 0.2677]])
tensor([[0.7527, 1.4189],
        [1.1324, 0.2974]])


In [17]:
# subtraction
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x - y
z = torch.sub(x, y)
print (z)

tensor([[0.0246, 0.3834],
        [0.8927, 0.6488]])
tensor([[0.4064, 0.8959],
        [0.4785, 0.7971]])
tensor([[-0.3818, -0.5125],
        [ 0.4142, -0.1483]])


In [18]:
# multiplication
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x * y
z = torch.mul(x,y)
print (z)


tensor([[0.1538, 0.8946],
        [0.9987, 0.1703]])
tensor([[0.8836, 0.1529],
        [0.7192, 0.8987]])
tensor([[0.1359, 0.1367],
        [0.7183, 0.1530]])


In [19]:
# division
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z1 = x / y
z1 = torch.div(x,y)
print(z1)

tensor([[0.3369, 0.8256],
        [0.3627, 0.9826]])
tensor([[0.7479, 0.1253],
        [0.4038, 0.9809]])
tensor([[0.4505, 6.5914],
        [0.8983, 1.0017]])


# Slicing

In [20]:
#Slicing
x = torch.rand(5,3)
print("Slicing")
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

Slicing
tensor([[0.9706, 0.2571, 0.4836],
        [0.8216, 0.7808, 0.9137],
        [0.8111, 0.7942, 0.8295],
        [0.5085, 0.4842, 0.9142],
        [0.2302, 0.7142, 0.4694]])
tensor([0.9706, 0.8216, 0.8111, 0.5085, 0.2302])
tensor([0.8216, 0.7808, 0.9137])
tensor(0.7808)
0.7807950973510742


# Reshaping Tensors

In [21]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

tensor([[-0.3667, -1.8421,  0.3171,  0.7261],
        [-0.0821,  1.1064,  0.8711, -0.6101],
        [-1.1239, -0.8854, -0.1076, -0.6568],
        [ 0.8878,  0.5640,  1.4915,  1.0753]])
tensor([-0.3667, -1.8421,  0.3171,  0.7261, -0.0821,  1.1064,  0.8711, -0.6101,
        -1.1239, -0.8854, -0.1076, -0.6568,  0.8878,  0.5640,  1.4915,  1.0753])
tensor([[-0.3667, -1.8421,  0.3171,  0.7261, -0.0821,  1.1064,  0.8711, -0.6101],
        [-1.1239, -0.8854, -0.1076, -0.6568,  0.8878,  0.5640,  1.4915,  1.0753]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# NumPy

In [22]:
# Numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# If the Tensor is on the CPU, they will share the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
# Numpy to Torch
print("Numpy to Torch")
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)


Numpy to Torch
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:
#They also share same memory
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Autograd Package

In [25]:
# The Autograd Package
print("Autograd Package")
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):

    random = False
    if random:    
        random_inputs = torch.randn(4)
        print(random_inputs)
    else:
        random_inputs = 3

    # just a dummy example
    model_output = (weights*random_inputs).sum() # [1,1,1,1]*3 = [3,3,3,3] => 3*4 = 12
    print(model_output)
    
    model_output.backward() # calculate gradients 
    print(weights.grad) # dLoss/dw
    print(weights)

    with torch.no_grad():
        weights -= 0.1 * weights.grad
        print(weights)

    # this is important! It affects the final weights & output
    weights.grad.zero_() # the gradient will accumulate otherwise

print(weights)
print(model_output)

Autograd Package
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([1., 1., 1., 1.], requires_grad=True)
tensor([0.7000, 0.7000, 0.7000, 0.7000], requires_grad=True)
tensor(8.4000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.7000, 0.7000, 0.7000, 0.7000], requires_grad=True)
tensor([0.4000, 0.4000, 0.4000, 0.4000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.4000, 0.4000, 0.4000, 0.4000], requires_grad=True)
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
