In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F # Only for leaky_relu
x = torch.tensor([-1.0, 1.0, 2.0, 3.0])

In [2]:
# softmax
output = torch.softmax(x, dim=0) # standalone function used outside of the model
print(output)
sm = nn.Softmax(dim=0) # module that can be included in a neural network model
output = sm(x)
print(output)
total = torch.sum(output)
print(total)

tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor(1.)


In [3]:
# sigmoid
output = torch.sigmoid(x)
print(output)
s = nn.Sigmoid()
output = s(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])
tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [4]:
# hyperbolic tangent
output = torch.tanh(x)
print(output)
t = nn.Tanh()
output = t(x)
print(output)

tensor([-0.7616,  0.7616,  0.9640,  0.9951])
tensor([-0.7616,  0.7616,  0.9640,  0.9951])


In [5]:
# relu
output = torch.relu(x)
print(output)
relu = nn.ReLU()
output = relu(x)
print(output)

tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


In [6]:
# leaky relu
output = F.leaky_relu(x)
print(output)
lrelu = nn.LeakyReLU()
output = lrelu(x)
print(output)

tensor([-0.0100,  1.0000,  2.0000,  3.0000])
tensor([-0.0100,  1.0000,  2.0000,  3.0000])


In [7]:
import torch
import torch.nn as nn

class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out
      
input_size = 10
hidden_size = 20
net = NeuralNet(input_size, hidden_size)
input_tensor = torch.rand(1, input_size)
print(input_tensor)
output_tensor = net.forward(input_tensor)
print(output_tensor)

tensor([[0.7805, 0.4749, 0.6590, 0.5317, 0.6643, 0.3877, 0.2508, 0.8464, 0.7038,
         0.4914]])
tensor([[0.5426]], grad_fn=<SigmoidBackward0>)


In [8]:
import torch
import torch.nn as nn
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, 1)
        
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out

input_size = 10
hidden_size = 20
net = NeuralNet(input_size, hidden_size)

# Convert the list to a Tensor
