In [8]:
# Construct a simple Linear Regression model
# Define the data
# Design model (input, output, forward pass with layers)
# construct loss and optimiser
# Training loop
  # forward to compute prediction and loss
  # backward to compute gradients
  #update weights
  
import torch
import torch.nn as nn

# Training samples
X = torch.tensor ([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor ([[3], [6], [9], [12]], dtype=torch.float32)
print(X)
print(Y)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [9]:
n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')

#samples: 4, #features: 1


In [10]:
# createa a test sample
X_test = torch.tensor([12], dtype=torch.float32)
print(X_test)

tensor([12.])


In [11]:
# Design model
input_size = n_features
output_size = n_features
print(input_size)
print(output_size)

1
1


In [12]:
# we call the model
model = nn.Linear(input_size, output_size)

"""
class LinearRegression(nn.Module):
  def __init__(self, input_dim, output_dim):
    super(LinearRegression, self).__init__()
    # define different layers
    self.lin = nn.Linear(input_dim, output_dim)
  def forward(self, x):
    return self.lin(x)
model = LinearRegression(input-size, output_size)
"""


print(f'prediction before training: f(10) = {model(X_test).item():.3f}')

prediction before training: f(10) = 3.711


In [13]:
# Define Loss and optimiser
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimiser = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [14]:
# training the model
for epoch in range(n_iters):

# predict = forward pass with our mode
  y_predicted = model(X)

# loss
  l = loss(Y, y_predicted)

# calculate gradients = backward pass
  l.backward()

# update weights
  optimiser.step()

# zero the gradients after updating
  optimiser.zero_grad()

  if epoch % 10 == 0:
    [w, b] = model.parameters()
    print('epoch', epoch+1, ': w =', w[0][0].item(), 'loss = ', l)

print(f'prediction after training: f(12) = {model(X_test).item():.3f}')

epoch 1 : w = 0.6234213709831238 loss =  tensor(47.1783, grad_fn=<MseLossBackward0>)
epoch 11 : w = 2.2051844596862793 loss =  tensor(1.5660, grad_fn=<MseLossBackward0>)
epoch 21 : w = 2.4717957973480225 loss =  tensor(0.3658, grad_fn=<MseLossBackward0>)
epoch 31 : w = 2.526505708694458 loss =  tensor(0.3158, grad_fn=<MseLossBackward0>)
epoch 41 : w = 2.5467827320098877 loss =  tensor(0.2967, grad_fn=<MseLossBackward0>)
epoch 51 : w = 2.5611820220947266 loss =  tensor(0.2794, grad_fn=<MseLossBackward0>)
epoch 61 : w = 2.5743072032928467 loss =  tensor(0.2632, grad_fn=<MseLossBackward0>)
epoch 71 : w = 2.5869076251983643 loss =  tensor(0.2478, grad_fn=<MseLossBackward0>)
epoch 81 : w = 2.599114179611206 loss =  tensor(0.2334, grad_fn=<MseLossBackward0>)
epoch 91 : w = 2.6109566688537598 loss =  tensor(0.2198, grad_fn=<MseLossBackward0>)
prediction after training: f(12) = 32.569
