In [1]:
import numpy as np

X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([3, 6, 9, 12], dtype=np.float32)

w = 0.0

# model output
def forward(x):
  return w*x

# loss = MSE
def loss(y, y_pred):
  return ((y_pred-y)**2).mean()

def gradient(x, y, y_pred):
  return np.dot(3*x, y_pred-y)

print(f'Prediction before training: f(10) = {forward(10)}')

learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):

  # dw = np.zeros_like(w)
  # print(dw)

# predict = forward pass
  y_pred = forward(X)
  print(y_pred)

  # loss
  l = loss(Y, y_pred)
  print(l)

  # calculate gradients
  dw = gradient(X, Y, y_pred)
  print(dw)

  # update weights
  w -= learning_rate * dw
  print(learning_rate)

  # output the intermediate results
  print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

  # dw = np.zeros_like(w)
  # print(dw) 

  # if epoch % 1 == 0:
  #   print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
  print()

print(f'prediction after training: f(12) = {forward(12):.3f}')
print('w is ', w)

Prediction before training: f(10) = 0.0
[0. 0. 0. 0.]
67.5
-270.0
0.01
epoch 1: w = 2.700, loss = 67.50000000

[ 2.7  5.4  8.1 10.8]
0.6749997
-26.999992
0.01
epoch 2: w = 2.970, loss = 0.67499971

[ 2.97  5.94  8.91 11.88]
0.006749998
-2.6999996
0.01
epoch 3: w = 2.997, loss = 0.00675000

[ 2.997  5.994  8.991 11.988]
6.7499874e-05
-0.26999974
0.01
epoch 4: w = 3.000, loss = 0.00006750

[ 2.9996998  5.9993997  8.9991    11.998799 ]
6.756533e-07
-0.027013063
0.01
epoch 5: w = 3.000, loss = 0.00000068

[ 2.99997  5.99994  8.99991 11.99988]
6.746916e-09
-0.0026993752
0.01
epoch 6: w = 3.000, loss = 0.00000001

[ 2.9999971  5.9999943  8.999991  11.999989 ]
6.139089e-11
-0.00025749207
0.01
epoch 7: w = 3.000, loss = 0.00000000

[ 2.9999995  5.999999   8.999998  11.999998 ]
2.1032065e-12
-4.720688e-05
0.01
epoch 8: w = 3.000, loss = 0.00000000

[ 3.  6.  9. 12.]
0.0
0.0
0.01
epoch 9: w = 3.000, loss = 0.00000000

[ 3.  6.  9. 12.]
0.0
0.0
0.01
epoch 10: w = 3.000, loss = 0.00000000

[ 3.  6